version: "3.9"

services:
  app:
    build:
      context: .
    env_file:
      - .env
    volumes:
      - ./backend:/app
    restart: on-failure
    command: >
      sh -c "python manage.py wait_db && python manage.py runserver 0.0.0.0:8000"

  db:
    image: mysql:8
    ports:
      - "3308:3306"
    env_file:
      - .env
    volumes:
      - ./mysql:/var/lib/mysql
    restart: on-failure

  web:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./client:/usr/share/nginx/html
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ./backend/static:/usr/usr/share/nginx/doc

  celery:
    build:
      context: .
    env_file:
      - .env
    volumes:
      - ./backend:/app
    restart: on-failure
    depends_on:
      - redis
    command: >
      sh -c "celery -A configs worker -l info"

  redis:
    image: redis:alpine
    restart: on-failure

  flower:
    image: mher/flower:0.9.7
    depends_on:
      - redis
    restart: on-failure
    ports:
      - "5555:5555"
    command: [ "flower", "--broker=redis://redis:6379", "--port=5555" ]

