version: "3.9"

services:
  app:
    build:
      context: .
    env_file:
      - .env
    volumes:
      - ./backend:/app
    depends_on:
      - db
    restart: on-failure
    command: >
      sh -c "python manage.py wait_db && python manage.py runserver 0.0.0.0:8000"

  db:
    image: mysql:8
    ports:
      - "3308:3306"
    env_file:
      - .env
    volumes:
      - ./mysql:/var/lib/mysql
    restart: on-failure

  web:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./client:/usr/share/nginx/html
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ./backend/static:/usr/usr/share/nginx/doc