# Generated by Django 4.2.2 on 2023-06-25 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='carmodel',
            options={'ordering': ('id',)},
        ),
        migrations.AddField(
            model_name='carmodel',
            name='body',
            field=models.CharField(choices=[('Hatchback', 'Hatchback'), ('Sedan', 'Sedan'), ('MUV / SUV', 'Muv Suv'), ('Coupe', 'Coupe'), ('Convertible', 'Convertible'), ('wagon', 'Wagon'), ('Van', 'Van'), ('Jeep', 'Jeep')], default='Jeep', max_length=11),
            preserve_default=False,
        ),
    ]
